# Generated by Django 5.2.8 on 2025-11-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(
                related_name="orders", to="materials.discount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="taxes",
            field=models.ManyToManyField(related_name="orders", to="materials.tax"),
        ),
    ]
